### PR TITLE
Add BasePath Support for #81

### PR DESCRIPTION
**Pull request by dawinter**
https://github.com/maxdome/swagger-combine/issues/81

### CODE REVIEW

**Comment by dawinter** [comment]
@fabsrc May want to look into?

**Comment by fabsrc** [comment]
Thanks for your PR @dawinter

The functionality makes sense, however this seems like a breaking change to me, because it changes the default logic which might break existing services that are using this module. 

Could you maybe add an option to activate this functionality (similar to existing options like `includeParameters`)?

Also tests would be great.

**Comment by dawinter** [comment]
Thanks for the first review. First I thought it must be a bug. But you are right the testcase shows that the error behavoir was expected. I added a parameter and a test case. 

Please review again. Feel free to change the parameter name or the level of the parameter.

**Comment by fabsrc** [comment]
Looks good to me. 🙂 
Could you please also add some documentation for this feature?

**Comment by dawinter** [comment]
documentation added ad base path option moved to the paths section to respect the structure of options.

**Pull request merged**
